################################################################################
## CloudFormation Template for Lambda Function Triggered by S3 PutObject Event##
## Author: BMV System Integration Pvt Ltd				      ##
## Version: 1.0                                    			      ##
## Publish Date: 2023-10-03                                                   ##
################################################################################
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for Lambda Function Triggered by S3 PutObject Event

Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: transcribecodebucket
        S3Key: lambda_function.zip
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.9 # Change to your desired runtime
      Timeout: 60 # Change as needed

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - arn:aws:s3:::transcribecodebucket/*
                  - arn:aws:s3:::audiototextbmv/*
Outputs:
  LambdaFunctionArn:
    Description: The ARN of the Lambda function
    Value: !GetAtt MyLambdaFunction.Arn

